# Generated by Django 2.2.6 on 2019-10-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191030_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Answer'),
        ),
    ]
