# Generated by Django 2.2.6 on 2019-10-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191024_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
