# Generated by Django 2.2.6 on 2019-10-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191024_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Response'),
        ),
    ]
